version: "3.5"

services:
        forpdi-database:
                image: mysql:5.7
                environment:
                        MYSQL_ROOT_PASSWORD: docker12345
                        MYSQL_DATABASE: plataformafor
        forpdi-backend:
                build: ./backend-java
                image: platfor-backend
                volumes:
                        - pdfs:/var/forpdi/pdfs
                        - arquivos:/var/forpdi/files
                depends_on:
                        - forpdi-database
                ports:
                        - 8009:8009
                        - 8080:8080
        forpdi-frontend:
                build: ./frontend-web
                image: platfor-front
                depends_on:
                        - forpdi-backend
                ports:
                        - 80:80
volumes:
    pdfs:
    arquivos:
